language: python
services:
  - docker
env:
  - KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/graphql
jobs:
  include:
    - &test-recipes
      stage: Test *.ipynb in recipes
      script:
        - docker pull ${DOCKER_IMAGE}
        - docker run --env KILI_API_ENDPOINT=${KILI_API_ENDPOINT} ${DOCKER_IMAGE} env | grep KILI
        - >
          docker run
          --env KILI_API_ENDPOINT=${KILI_API_ENDPOINT}
          --env KILI_USER_EMAIL=${KILI_USER_EMAIL}
          --env KILI_USER_PASSWORD=${KILI_USER_PASSWORD}
          ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
              git clone --branch ${TRAVIS_BRANCH} https://github.com/marcenacp/kili-playground.git && \
              jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --execute /root/kili-playground/${NOTEBOOK_PATH}"
      env:
        - DOCKER_IMAGE=continuumio/anaconda3
        - NOTEBOOK_PATH=recipes/image-object-detection-with-yolo/main.ipynb
    # - <<: *test-recipes
    #   env:
    #     - DOCKER_IMAGE=continuumio/anaconda3
    #     - NOTEBOOK_PATH=recipes/image-object-detection-with-yolo/main.ipynb
