language: python
services:
  - docker

before_install:
  - docker pull continuumio/anaconda3
  - docker run continuumio/anaconda3 /bin/sh -c "ls -lrt"
  - docker run continuumio/anaconda3 /bin/sh -c "cd /root; ls -lrt"
  - docker run continuumio/anaconda3 /bin/sh -c "cd /dev; ls -lrt"
  - docker run continuumio/anaconda3 /bin/sh -c "cd /home; ls -lrt"
  - docker run continuumio/anaconda3 /bin/sh -c "cd ~; ls -lrt"
