language: python
services:
  - docker
jobs:
  include:
    - &test-recipes
      stage: Test *.ipynb in recipes
      script:
        - docker pull ${DOCKER_IMAGE}
        - docker run ${DOCKER_IMAGE} /bin/sh -c "jupyter kernelspec list"
        - >
          docker run ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
              git clone --branch ${TRAVIS_BRANCH} https://github.com/kili-technology/kili-playground.git && \
              jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --execute /root/kili-playground/${NOTEBOOK_PATH}"
      env:
        - DOCKER_IMAGE=continuumio/anaconda3
        - NOTEBOOK_PATH=recipes/image-object-detection-with-yolo/main.ipynb
    # - <<: *test-recipes
    #   env:
    #     - DOCKER_IMAGE=continuumio/anaconda3
    #     - NOTEBOOK_PATH=recipes/image-object-detection-with-yolo/main.ipynb
